# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdd_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pdd_message.proto\"\xd5\x01\n\x0fTitanDownstream\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08protocol\x18\x02 \x01(\r\x12\x11\n\terrorCode\x18\x03 \x01(\r\x12\x0f\n\x07\x62izCode\x18\x04 \x01(\r\x12\x13\n\x0b\x62izErrorMsg\x18\x05 \x01(\t\x12\x10\n\x08\x63ompress\x18\x06 \x01(\r\x12\x11\n\textension\x18\t \x01(\x0c\x12\x0c\n\x04\x62ody\x18\n \x01(\x0c\x12\x15\n\rdownstreamSeq\x18\x0b \x01(\x04\x12\r\n\x05\x63onId\x18\x0c \x01(\x04\x12\r\n\x05\x63txId\x18\r \x01(\x04\"b\n\rMulticastLite\x12\x0f\n\x07\x62izType\x18\x01 \x01(\r\x12\x0f\n\x07groupId\x18\x02 \x01(\t\x12\r\n\x05msgId\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x0f\n\x07needAck\x18\x05 \x01(\x08\"\x9b\x01\n\x0fMulticastNotify\x12\x0f\n\x07\x62izType\x18\x01 \x01(\r\x12\x0f\n\x07groupId\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\n\n\x02ts\x18\x04 \x01(\x04\x12\x13\n\x0bminInterval\x18\x05 \x01(\r\x12\x13\n\x0bmaxInterval\x18\x06 \x01(\r\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\x12\x0f\n\x07needAck\x18\x08 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pdd_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TITANDOWNSTREAM']._serialized_start=22
  _globals['_TITANDOWNSTREAM']._serialized_end=235
  _globals['_MULTICASTLITE']._serialized_start=237
  _globals['_MULTICASTLITE']._serialized_end=335
  _globals['_MULTICASTNOTIFY']._serialized_start=338
  _globals['_MULTICASTNOTIFY']._serialized_end=493
# @@protoc_insertion_point(module_scope)
